1.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
2.Create an array of 20 linearly spaced points between 0 and 1
3.declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix. 
4.using the previously defined matrix print rows 1,5,6
5.using the previously defined matrix print elemnts from 3rd row  to 10th row
6.using the previously defined matrix print all elemtnts from 4th column to 8th column
7.using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column
8.write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same .
9.write the commands to get standard deviation, mean ,mode,median for a given vector 

In [1]:
#1.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
import numpy as np
np.random.randn(25)

array([-0.24403147, -2.20264648,  0.09996609,  0.70640936,  0.43341709,
        0.46010972, -1.45205839, -1.99432403, -0.51427479, -0.39364683,
       -0.54067446, -0.00860112, -0.39598026, -0.33382695, -0.45992423,
        1.13667345,  0.93978114,  0.85649104, -1.28310983,  2.02536301,
        0.1202737 ,  0.89478743, -0.38735101, -0.40797591,  0.37696539])

In [2]:
#2.Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
#3.declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix.
x=np.arange(1,101).reshape(10,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [10]:
#4.using the previously defined matrix print rows 1,5,6
print(x[1])
print(x[5])
print(x[6])

[11 12 13 14 15 16 17 18 19 20]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]


In [5]:
#5.using the previously defined matrix print elemnts from 3rd row  to 10th row
x[3:11]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
#6.using the previously defined matrix print all elemtnts from 4th column to 8th column
x[:,4:9]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

In [7]:
#7.using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column
x[3:6,2:9]

array([[33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59]])

In [18]:
#8.write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all 
#random points like are almost same .
array = np.random.randint(0,1,size=1000)
print(array);

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [13]:
#9.write the commands to get standard deviation, mean ,mode,median for a given vector
values = [99,86,87,88,111,86,103,87,94,78,77,85,86]
a=np.mean(values)
print(a)

89.76923076923077


In [15]:
#median
b=np.median(values)
print(b)

87.0


In [16]:
#mode
import statistics as st
z=st.mode(values)
print(z)

86


In [17]:
#standard deviation
arr = [20, 2, 7, 1, 34]
np.std(arr)

12.576167937809991